# Generated by Django 4.2.3 on 2023-09-25 06:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_info_remove_producer_field2'),
        ('candy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candy',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Цена (руб)'),
        ),
        migrations.AddField(
            model_name='candy',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.producer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='candy',
            name='rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка от владельца'),
        ),
        migrations.AddField(
            model_name='candy',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Вес (грамм)'),
        ),
    ]
