# Generated by Django 4.2.3 on 2023-09-25 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0002_candy_price_candy_producer_candy_rate_candy_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candy',
            options={'verbose_name': 'Конфета', 'verbose_name_plural': 'Конфеты'},
        ),
        migrations.AlterField(
            model_name='candy',
            name='rate',
            field=models.IntegerField(default=1, help_text='От 1 до 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка от владельца'),
        ),
    ]
