# Generated by Django 4.2.3 on 2023-09-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='Никнейм')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('info', models.TextField(verbose_name='dfdfdfdf')),
            ],
            options={
                'verbose_name': 'Владелец конфеты',
                'verbose_name_plural': 'Владельцы конфет',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='Никнейм')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('inn', models.CharField(max_length=13, verbose_name='ИНН')),
                ('field2', models.CharField(max_length=1212)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
    ]
